// data.js — Armani Cunningham portfolio content. Faithful to the Wix site:
// same pages, same sections, same text. Each gallery lists media/<file> names.
window.SITE = {
  // nav order matches Wix; Resources is a dropdown with Vocab + Animation Vocab
  nav: [
    { slug: "home", title: "Home" },
    { slug: "junior-mastery", title: "Junior Mastery" },
    { slug: "animation", title: "Animation" },
    { slug: "digital-arts-1", title: "Digital Arts 1" },
    { slug: "digital-arts-2", title: "Digital Arts 2" },
    { slug: "portfolio", title: "Portfolio" },
    { slug: "ace", title: "ACE" },
    { slug: "image-editing", title: "Image Editing" },
    { slug: "resources", title: "Resources", children: [
      { slug: "vocab", title: "Vocab" },
      { slug: "animation-vocab", title: "Animation Vocab" },
    ]},
  ],

  pages: {
    home: { type: "home" },

    "junior-mastery": { type: "sections", title: "Junior Mastery", sections: [
      { heading: "Junior Mastery — Week 1",
        body: "Project one was building the plane layout. This is the final week 1 image, plus a collision error I hit (by spamming space to look back and forth and moving left/right I could clip through the wall) and an inside view of the plane.",
        images: ["Screenshot 2026-04-30 at 2.14.21 PM.png","Screenshot 2026-04-30 at 2.14.47 PM.png","Screenshot 2026-04-30 at 2.27.18 PM.png","Screenshot 2026-05-04 at 1.43.26 PM.png"] },
    ]},

    animation: { type: "canva", title: "Animation",
      body: "This site takes you to my animation page, hosted on Canva!",
      canva: "https://ethersonmastery2025.my.canva.site/armanicunningham",
      images: ["Screenshot 2025-10-06 at 9.27.59 AM.png","Screenshot 2025-10-15 at 8.27.05 AM.png","image.png"] },

    "digital-arts-1": { type: "sections", title: "Digital Arts 1", sections: [
      { heading: "Final SkillShare Projects", sub: "Fashion Glitch",
        item: "Final Project 1",
        body: "This is the final glitch effect project following the tutorial linked below. I had to use various hue saturation effects, and a layer mask.",
        note: "1 / 11",
        images: ["armanicunninghamphotoshop1.jpg","armanicunninghamphotoshop2.jpg","armanicunninghamphotoshop3.jpg","armanicunninghamphotoshop4.jpg"] },
      { heading: "SkillShare Project 2", sub: "Easily Make This Paper Cutout Style Graphic Using Adobe Photoshop's AI",
        body: "This is another tutorial I did that is putting images in texts, through clip masking. I had to get images that I generated with gemini and firefly, and then I used layers and clip masking to mask the images to the text that I clipped into shapes.",
        item: "AAST Water",
        caption: "This is the final product. I updated the two placeholders, and this was the final look. Overall, I'm really happy with how it came out. I learned a few skills such as cropping shapes and formatting text into shapes.",
        note: "Double-Click on the gallery to see the learning process from start to finish! (1 / 4)",
        images: ["AAST Water.jpg"] },
      { heading: "Skillshare Project 1", sub: "Photoshop Workflows — Movie Poster",
        item: "Final poster",
        caption: "I added the text at the top, made sure all the cropping and everything was ready, and then it was done! A good learning experience — I already knew a lot of this, but I learned more about cropping and selecting, and using layers since I had to move the big businessman's arm over the table layer but keep his body under it.",
        note: "Double-Click on the gallery to see the learning process from start to finish! (1 / 3)",
        images: ["Banker Vs Farmer.jpg","pexels-antonius-ferret-5275781.jpg","maxresdefault (1).jpg"] },
      { heading: "Inktober Work", sub: "Halloween String Lights",
        body: "Inktober is a yearly event for artists, occurring every Halloween, with a daily prompt that you make in black and white each day based on the prompt. Prompts: Award · Vacant · Lesson · Skeletal · Onion · Rowdy · Firefly · Button · Blast.",
        images: "INKTOBER" },
    ]},

    "digital-arts-2": { type: "sections", title: "Digital Arts and Design 2", sections: [
      { heading: "Digital Branding Assets",
        images: ["Untitled (2).png","Untitled (3).png","Untitled (4).png","Untitled (5).png","Untitled (6).png"] },
      { heading: "Adobe Express Animation",
        body: "For my animation video in Adobe Express, I used T's as the border and a bouncing effect. I thought it represented my brand idea well with the purple, white and black.",
        video: "11 - ArmaniCunninghamExpressAnimation.mp4", images: [] },
      { heading: "Typography Challenge", item: "Old design", note: "1 / 2", images: [] },
      { heading: "Famous Quote Typography",
        body: "For this typography project I chose the quote \"So many books, so little time.\" I made the \"many\" text bigger and \"little\" smaller to show the importance of those words. I added B's on the side to look like book binding and to fill the empty space. I'm happy with how it came out — the simplistic, empty look makes it better.",
        images: ["Untitled.png"] },
      { heading: "Typography Album Poster",
        body: "For this CD cover I did the band Living Tombstone and the FNAF songs they make. I chose green and orange because it's their logo, and the animatronics' colors for the FNAF text. To add structure I layered T's around the corner.",
        images: ["Armani Cunningham Typography 13.25.34.png"] },
      { heading: "Infographic Understanding", item: "Brand Package Infographic",
        body: "Creating a brand involves identity, presence, consistency, and uniqueness. You need consistent colors, fonts and images across all your branding, and it has to be relevant to you. You don't want a whole fake online persona that's super different from your real personality. You also shouldn't copy what someone else has — have your own unique brand even if you share the same niche.",
        note: "1 / 2", images: ["infographic.png"] },
      { heading: "Creating My Brand", item: "Business Card Front", note: "A little about me! (1 / 4)",
        images: ["Buisness Card Front.png","ArmanICunninghamBuisnessCardBack.png","ArmaniCunninghamYoutubeThumb.png","ArmaniCunningham_InstagramThumbnail.png","Screenshot 2026-01-26 at 2.23.22 PM.png"] },
    ]},

    portfolio: { type: "text", title: "My Portfolio",
      body: "Portfolio coming soon — see my work on the <a href='#/digital-arts-1'>Digital Arts</a> and <a href='#/ace'>ACE</a> pages.",
      images: ["Screenshot 2025-10-07 at 1.12.43 PM.png"] },

    ace: { type: "sections", title: "ACE", sections: [
      { heading: "Adobe Premiere Certification", images: [] },
      { heading: "Adobe Photoshop Certification",
        body: "I am officially certified in Adobe Photoshop! I'll have to retake it every 3 years, but I'm very proud of this achievement! I was very stressed when I clicked submit but I passed with a pretty high score!  (If you wish to verify the certificate, follow the steps on the bottom-left of it.)",
        images: ["Screenshot 2025-12-12 at 12.46.49 PM.png"] },
      { heading: "Adobe Animate Certification",
        body: "I am officially certified in Adobe Animate! I'll have to retake it every 3 years, but I'm very proud of this achievement! It was a pretty challenging test and tough to remember some tool locations, but I pulled through!  (Verify via the steps on the bottom-left of the certificate.)",
        images: ["Screenshot 2025-12-12 at 12.46.40 PM.png"] },
      { heading: "Digital Media 2 Certification",
        body: "I am now certified in Digital Media 2! I passed the test on 11/14/25. It means I understand: 1. Planning, Design, and Development · 2. Digital Audio · 3. 2D Animation · 4. Digital Video · 5. Team Activities · 6. Copyright Laws, Ethics, and Issues.",
        images: ["Screenshot 2025-12-12 at 12.36.14 PM.png"] },
      { heading: "Digital Media 1 Certification",
        body: "I am now certified in Digital Media 1! I passed the test on 12/12/25. It means I understand: 1. Design Process · 2. Color Theory · 3. Typography · 4. Vector Graphics · 5. Raster Images · 6. Project Management · 7. Careers and Employability.",
        images: ["Screenshot 2025-12-12 at 12.36.25 PM.png"] },
      { heading: "Read Across SC Competition", item: "Read Across SC Final",
        body: "Read Across South Carolina is a state competition for students grades K-12, themed around emphasizing reading across the state. You couldn't use AI and I didn't know how to draw well, so I used gradients as the background and images inside the text. I made this in Photoshop.",
        note: "Double-click to full-view (1 / 6)",
        images: ["Armanicunningham_ReadacrossSC.jpg"] },
      { heading: "Read Across SC Competition — Planning", item: "Planning 1",
        body: "For this competition AI use was NOT allowed, which made it more difficult — I used an image off Pexels to make a mask layer. I can't draw well, which made it a lot harder since I couldn't use AI and couldn't draw.",
        note: "1 / 2", images: [] },
      { heading: "AI Art Competition", item: "Final Picture",
        body: "This was the AI art I chose to submit, and it got into the competition! (2025 AI Art Competition presented by Comcast — \"Life Through AI Eyes,\" $1,000 in prizes, Arts Center of Greenwood.)",
        note: "1 / 5",
        images: ["Screenshot 2025-10-31 at 12.49.36 PM.png"] },
      { heading: "My Art (State Fair 2025)", images: ["Screenshot 2025-08-29 at 12.47.18 PM.png"] },
      { heading: "State Fair Photos 2025", item: "7AM",
        caption: "An image me and my friends took during our bus ride to the state fair. This was important because I got to learn a lot about them throughout the day.",
        note: "1 / 14", images: "STATEFAIR" },
    ]},

    "image-editing": { type: "sections", title: "Image Editing 1", sections: [
      { heading: "Image Editing 1", body: "This is all my work from my 24-25 image editing class!",
        images: ["British.jpg","Wig.jpg","Starfish.jpg","Greetings From Pewter City.jpg","Firefly (1).jpg","20250103_162021.jpg","IMG_3622.JPG"] },
    ]},

    resources: { type: "links", title: "Animation Resources", links: [
      { name: "Goblin Tools", url: "https://goblin.tools/" },
      { name: "Mind Map", url: "https://www.canva.com/design/DAGx1dC8NBE/LC58rnwIgI84mphZ4SWmtg/edit" },
      { name: "Unsplash", url: "https://unsplash.com/" },
      { name: "Pexels", url: "https://www.pexels.com/" },
      { name: "Canva Stock", url: "https://www.canva.com/features/free-stock-photos/" },
      { name: "FreePik", url: "https://www.freepik.com/" },
      { name: "Vecteezy", url: "https://www.vecteezy.com/" },
      { name: "Font Gen", url: "https://labs.google/gentype?authuser=0" },
      { name: "Location Release", url: "https://docs.google.com/document/d/1dVMiV9SanCAU3rXU-Qj4a0cnPuUI5_fey_UjwNeJYBk/edit" },
      { name: "Model Release", url: "https://docs.google.com/document/d/1xxx59X_NDwJwJNtERMY1ikS4vVDrTieOnlD3DO5SDFw/edit" },
    ]},

    vocab: { type: "vocab", title: "Vocab", terms: [
      { term: "Narrative", pos: "noun", def: "A spoken or written account of connected events; a story." },
      { term: "Arbitrary", pos: "adjective", def: "Based on random choice or personal whim, rather than any reason or system." },
      { term: "Authentic", pos: "adjective", def: "Of undisputed origin; genuine." },
      { term: "Nuanced", pos: "adjective", def: "Characterized by subtle shades of meaning or expression." },
      { term: "Generic", pos: "adjective", def: "Lacking distinction; general." },
      { term: "Trauma", pos: "noun", def: "A deeply distressing or disturbing experience." },
      { term: "Embodying", pos: "verb", def: "Be an expression of or give a tangible or visible form to (an idea, quality, or feeling)." },
    ]},

    "animation-vocab": { type: "vocab", title: "Animation Vocab", terms: [
      { term: "Rigging", def: "Adding animation data to Photoshop / Illustrator files so they can move in Adobe Character Animator." },
      { term: "Puppet", def: "A digital character created from layered files that can be rigged and animated." },
      { term: "Rig Mode", def: "The workspace for setting up a puppet's structure — handles, tags, sticks, and behaviors." },
      { term: "Handles", def: "Points that define where movement happens on a puppet." },
      { term: "Sticks", def: "Lines that create rigidity between handles, functioning like bones." },
      { term: "Tags", def: "Labels that identify body-part controls." },
      { term: "Behaviors", def: "Prebuilt animation controls that respond to input — e.g. Face, Dragger, Walk, Lip Sync." },
      { term: "Dragger", def: "A behavior that lets you click and drag puppet parts while animating." },
      { term: "Hierarchy", def: "The layer order that tells Character Animator how to organize puppet parts." },
      { term: "Origin Point", def: "The central pivot point for a layer's rotation or movement." },
      { term: "Parent / Child Relationship", def: "Rigging where child parts move in response to parent parts." },
      { term: "Anchor Point", def: "A fixed point that keeps puppet parts stationary." },
      { term: "Trigger", def: "A behavior that switches or reveals specific puppet parts." },
      { term: "Physics Behavior", def: "A setting that enables natural reactions to gravity or collisions." },
      { term: "Calibration", def: "Aligning the webcam and microphone for facial-expression and voice tracking." },
    ]},
  },
};
